PLF-7093 Upgrade ES to version 5.2
exo-addons/exo-es-embedded pull request #9
Opened 2017-03-06 23:13 UTC by mgreau

2017-03-07 14:48 UTC, vsellier commented on pom.xml
> +    <org.apache.tika.version>1.14</org.apache.tika.version>
Add a comment to explain it's needed by the ingest attachement plugin

2017-03-07 14:48 UTC, vsellier commented on war/src/main/resources/log4j2.xml
> +</Configuration>
WDYT of creating an elasticsearch.log in the PLF log directory ?

2017-03-07 16:38 UTC, boubaker commented on pom.xml
> +    <org.apache.tika.version>1.14</org.apache.tika.version>
done

2017-03-07 16:39 UTC, boubaker commented on war/src/main/resources/log4j2.xml
> +</Configuration>
I can't configure something generic to Tomcat and JBoss here.
We wasn't doing this before, I will create a dedicated JIRA issue for this, WDYT ?

2017-04-05 14:15 UTC, thomasdelhomenie requested changes

2017-04-05 14:15 UTC, thomasdelhomenie commented on pom.xml
> +        <artifactId>maven-depmgt-pom</artifactId>
Is it really necessary to import this pom ? It is already imported by the pom org.exoplatform.platform:platform.

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +      resourceAsStream.close();
Should be moved in a finally to always close the stream.

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +      settings.put("path.data", System.getProperty(pathData));
It will not work in the case the path is ${my.var}/toto for example.

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
Aren't these variables replaced at https://github.com/exo-addons/exo-es-embedded/pull/9/files#diff-b9f550ab159eb110ac2599ea6cfdabfdR22 ? I think it used to work in previous versions. Is it due to a change in ES 5 ?

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedNode.java
>      this.version = version;
The version is not used anymore, it can be removed.

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> -path.plugins: es/plugins
It was used to install new plugins (by customers for example). What is the new path ? Is it still possible ?

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> +network.host: _local_
Can you add back the comments ?

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> -index.auto_expand_replicas: 0-5
These 2 paramaters are not needed anymore ?

2017-04-05 14:15 UTC, thomasdelhomenie commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> +# Disable dynamic scripting
Why do we disable dynamic scripting in embedded mode ?

2017-04-06 11:07 UTC, boubaker commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> -path.plugins: es/plugins
Yes, this property/capability was removed:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html

2017-04-06 11:10 UTC, boubaker commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> -index.auto_expand_replicas: 0-5
c.f
https://github.com/exo-addons/exo-es-embedded/pull/7#discussion_r104106658

2017-04-06 11:48 UTC, boubaker commented on pom.xml
> +        <artifactId>maven-depmgt-pom</artifactId>
done

2017-04-06 11:49 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +      resourceAsStream.close();
done with try-with-resources Statement

2017-04-06 11:51 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
Unfortunately, this can't manage this using ES 5 API (breaking change, yes). I modified the implementation to make it more generic and flexible.

2017-04-06 11:53 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +      settings.put("path.data", System.getProperty(pathData));
I modified the implementation to make it more generic and flexible. (even with variables cascade `${path.data:${path.custom\}/custom}/es` )

2017-04-06 11:53 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedNode.java
>      this.version = version;
done

2017-04-06 11:53 UTC, boubaker commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> +network.host: _local_
done

2017-04-06 12:04 UTC, boubaker commented on war/src/main/webapp/WEB-INF/elasticsearch.yml
> +# Disable dynamic scripting
Not used in our context, this may disable extra processing while querying. Set to default anyway, the embedded mode is used for test purposes.

2017-04-10 08:35 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
Does it mean we will still be able to override any default ES configuration by settings them in exo.properties with the prefix "es." (as defined in the documentation : https://www.exoplatform.com/docs/public/topic/PLF44/PLFAdminGuide.Configuration.ElasticSearch.html?resultof=%22%65%6c%61%73%74%69%63%73%65%61%72%63%68%22%20) ?
If so, why changing the value of "cluster.name" for example (https://github.com/exo-addons/exo-es-embedded/pull/9/files#diff-d4893754c9fae24a1defee0099606c50R6) ?

2017-04-10 10:58 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
the es.*** properties aren't taken into account anymore. The ES properties couldn't be injected by System properties anymore, it's injected via System Environment variables only when launching  ES using command line on standalone mode.
So the `./elasticsearch -Des.path.data=XYZ` is now `./elasticsearch -Ees.path.data=XYZ`
So I had to make a change in order to remake the exo.properties variables taken into account. See this:
https://github.com/exo-addons/exo-es-embedded/pull/9/files#diff-3a01cbd89b06b166d1ae0267f0fbf0a5R59

2017-04-11 16:07 UTC, thomasdelhomenie commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
OK, so if we cannot override ES properties via exo.properties (system properties), we need another to do it. We should add a new properties to define a custom location for the file elasticsearch.yml. WDYT ?

2017-04-11 17:00 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
Sounds a good alternative

2017-04-12 16:48 UTC, boubaker commented on war/src/main/java/org/exoplatform/addons/es/EmbeddedESStartupServlet.java
> +    } else if (pathData.startsWith("${")) {
Done

2017-04-14 16:00 UTC, thomasdelhomenie approved these changes

2017-05-17 17:29 UTC, merged